# Generated by Django 3.0.4 on 2020-03-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ceaser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
