# Generated by Django 3.0.4 on 2020-03-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ceaser', '0002_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(default='', max_length=50)),
                ('document_img', models.ImageField(default='', upload_to='media/images')),
                ('document_desc', models.CharField(default='', max_length=500)),
                ('document_date', models.DateTimeField()),
            ],
        ),
    ]
