# Generated by Django 3.0.4 on 2020-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ceaser', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateField(),
        ),
    ]
