# Generated by Django 3.0.4 on 2020-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ceaser', '0004_auto_20200325_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_img',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
